apiVersion: v1
kind: Service
metadata:
  name: go-service-nodeport
spec:
  type: NodePort
  selector:
    app: go-app
  ports:
    - protocol: TCP
      port: 80           # Service Port
      targetPort: 8080   # Container Port
      nodePort: 32667    # <--- The Magic Number (Firewall is already open for this)
